Add option to skip dot generation
savvasdalkitsis/module-dependency-graph pull request #8
Opened 2023-05-31 21:01 UTC by changusmc

In a large project with 350 nodes and 8000+ edges, it takes 4 hours to convert the `dot` file to `svg`. This adds an option to leave the `dot` file without an post processing which takes a few seconds.

2023-05-31 21:13 UTC, savvasdalkitsis requested changes
Looks good to me but i think the name `autoGenerateDot` might be a bit confusing as it might indicate that the dot file itself won't be generated.

Can i recommend something like `transformDot`?

2023-06-02 16:30 UTC, changusmc commented on src/main/groovy/com/savvasdalkitsis/module/deps/graph/ModuleDependencyGraphPlugin.groovy
> +                def autoGenerateDot = true
```suggestion
                def transformDot = true
```

2023-06-02 16:30 UTC, changusmc commented on src/main/groovy/com/savvasdalkitsis/module/deps/graph/ModuleDependencyGraphPlugin.groovy
> +                if (project.hasProperty('autoGenerateDot')) {
```suggestion
                if (project.hasProperty('transformDot')) {
```

2023-06-02 16:30 UTC, changusmc commented on src/main/groovy/com/savvasdalkitsis/module/deps/graph/ModuleDependencyGraphPlugin.groovy
> +                    autoGenerateDot = Boolean.parseBoolean(project.property('autoGenerateDot').toString())
```suggestion
                    transformDot = Boolean.parseBoolean(project.property('transformDot').toString())
```

2023-06-02 16:30 UTC, changusmc commented on src/main/groovy/com/savvasdalkitsis/module/deps/graph/ModuleDependencyGraphPlugin.groovy
> +                if (autoGenerateDot) {
```suggestion
                if (transformDot) {
```

2023-06-02 16:30 UTC, changusmc commented on src/main/groovy/com/savvasdalkitsis/module/deps/graph/ModuleDependencyGraphPlugin.groovy
> +                if (autoGenerateDot && autoOpenGraph) {
```suggestion
                if (transformDot && autoOpenGraph) {
```

2023-06-02 16:30 UTC, changusmc commented on README.md
> +### Auto generate dot file
```suggestion
### Transform dot file
```

2023-06-02 16:30 UTC, changusmc commented on README.md
> +By default, the command line tool `dot` will be used to generate an output defined in the
```suggestion
By default, the command line tool `dot` will be used to transform an output defined in the
```

2023-06-02 16:30 UTC, changusmc commented on README.md
> +./gradlew graphModules -PautoGenerateDot=false
```suggestion
./gradlew graphModules -PtransformDot=false      
```

2023-06-02 16:30 UTC, changusmc commented on README.md
> +autoGenerateDot=false
```suggestion
transformDot=false
```

2023-06-02 19:52 UTC, merged

2023-06-02 19:57 UTC, savvasdalkitsis commented
Published in v0.12